<#  08-disable-commerce.ps1  (v0.24.3 - bugfix 2: banks and every other shop-front the recipe ships)
    The QBox recipe starts whole folders (`ensure [qbx]`), so single resources cannot be commented out.
    This finds commerce resources by FOLDER NAME under <Base>\resources and writes `stop <name>` lines to
    <Base>\outbreak-commerce.cfg, which server.cfg execs at the end of the OUTBREAK block (after every ensure).
    PREVIEW by default; -Apply writes. Nothing is moved or deleted; delete a line from the file to restore.

      powershell -ExecutionPolicy Bypass -File .\setup\08-disable-commerce.ps1 -Base "C:\Outbreak\txData"
      powershell -ExecutionPolicy Bypass -File .\setup\08-disable-commerce.ps1 -Base "C:\Outbreak\txData" -Apply

    -Extra 'name1','name2' adds resources by exact folder name. -Keep 'name' spares one that matched a pattern.
#>
param([string]$Base, [switch]$Apply, [switch]$Jobs, [string[]]$Extra = @(), [string[]]$Keep = @())
. "$PSScriptRoot\_common.ps1"
$baseResolved = Resolve-Base -Base $Base
$res = Join-Path $baseResolved 'resources'
# exact names, plus patterns for the things that keep getting renamed between recipe versions
$exact = @('qbx_bank','qb-banking','Renewed-Banking','okokBanking','ps-banking','qbx_pawnshop','qbx_vehicleshop','qb-vehicleshop','qbx_vehiclesales','qbx_clothing','qb-clothing','qbx_shops','qb-shops','qbx_barbershop','qbx_tattooshop','qbx_ammunation','qb-weapons-shop','qbx_vehiclekeys','qbx_management','qbx_bossmenu','qbx_atm','qbx_cityhall')   # qbx_customs is KEPT on purpose: car mods stay, free (its price table needs editing by hand) + $Extra
$patterns = @('*bank*','*shop*','*ammunation*','*vehiclekeys*','*atm*','*pawn*','*dealer*','*sales*')
# -Jobs: the recipe's paid jobs, races, drugs, robberies with police, prison. Nothing in them fits a dead world,
# and several pay framework money. Kept: seatbelt, radialmenu, smallresources, adminmenu, chat_theme, binoculars, diving.
if ($Jobs) { $exact += @('qbx_busjob','qbx_taxijob','qbx_towjob','qbx_garbagejob','qbx_truckerjob','qbx_newsjob','qbx_recyclejob','qbx_mechanicjob','qbx_scrapyard','qbx_lapraces','qbx_streetraces','qbx_vineyard','qbx_weed','qbx_drugs','qbx_carwash','qbx_garages','qbx_idcard','qbx_scoreboard','qbx_jewelery','qbx_bankrobbery','qbx_storerobbery','qbx_houserobbery','qbx_truckrobbery','qbx_fireworks','xt-prison','ultra-voltlab') }
Write-Host "OUTBREAK - disable commerce resources (stop lines in outbreak-commerce.cfg)$(if ($Jobs) { ' + recipe jobs' })" -ForegroundColor White
if (-not $Apply) { Warn "PREVIEW - nothing will be changed. Add -Apply to write." }
if (-not (Test-Path -LiteralPath $res)) { Bad "resources folder not found: $res"; exit 1 }
$dirs = Get-ChildItem -LiteralPath $res -Recurse -Directory -ErrorAction SilentlyContinue | Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName 'fxmanifest.lua') }
$found = @{}
foreach ($d in $dirs) {
    $n = $d.Name
    if ($n -like 'outbreak_*') { continue }
    if ($Keep -contains $n) { continue }
    $hit = $false
    if ($exact -contains $n) { $hit = $true }
    else { foreach ($p in $patterns) { if ($n -like $p) { $hit = $true; break } } }
    if ($hit) { $found[$n] = $d.FullName }
}
if ($found.Count -eq 0) {
    Warn "no commerce resources found under $res. Look for the bank by hand:"
    Warn "  Get-ChildItem `"$res`" -Recurse -Directory | Where-Object Name -match 'bank|shop|atm' | Select-Object FullName"
    Warn "then re-run with -Extra 'thatname'"
    exit 0
}
foreach ($n in ($found.Keys | Sort-Object)) { Note ("stop {0,-28} {1}" -f $n, $found[$n]) }
if (-not $Apply) { Warn "$($found.Count) resource(s) would be stopped. Check the list (a wrong match = -Keep 'name'), then re-run with -Apply."; exit 0 }
$file = Join-Path $baseResolved 'outbreak-commerce.cfg'
$lines = @('## outbreak-commerce.cfg - generated by setup/08-disable-commerce.ps1 -Apply on ' + (Get-Date -Format 'yyyy-MM-dd HH:mm'),
           '## stop lines run after every ensure. Delete a line and restart to bring that resource back.')
foreach ($n in ($found.Keys | Sort-Object)) { $lines += "stop $n" }
if (Test-Path -LiteralPath $file) { Backup-File -Path $file | Out-Null }
Write-TextNoBom -Path $file -Lines $lines
Ok "$file written: $($found.Count) stop line(s)"
$cfg = Join-Path $baseResolved 'server.cfg'
if ((Test-Path -LiteralPath $cfg) -and -not ((Get-Content -LiteralPath $cfg -Raw) -match 'exec outbreak-commerce.cfg')) {
    Warn "server.cfg does not exec outbreak-commerce.cfg yet: run 07-update-cfg.ps1 -Apply (the v0.24.3 block has the exec line)"
}
Ok "Restart the server. Boot log should show those resources stopping after the outbreak_ ensures."
